### ISSUE TITLE
Comparison warnings

### ISSUE THREAD

**Issue by CryptoManiac** [CodesInChaos/Chaos.NaCl#11]
ge_double_scalarmult.cs

``` c#
                    for (b = 1; b <= 6 && (i + b) < 256; ++b)
                    {
                        if (r[i + b] != 0)
```

According to PVS studio, b <= 6 is always true. 

`V3063 A part of conditional expression is always true: b <= 6. ge_double_scalarmult.cs 20`

I've checked it and seen that results of running modified slide method 

``` c#
                    for (b = 1; /*b <= 6 &&*/ (i + b) < 256; ++b)
                    {
                        if (r[i + b] != 0)
```

are equivalent to given by the original implementation. 

Maybe I'm wrong here, but this seems very disturbing. Is this a consequence of some bug or we simply have an excessive checking here?

P.S. Tried to run this code in the debugger, and seen few cases when b is greater than 6. So, this must be a PVS issue.

**Comment by CodesInChaos** [comment]
Did you figure out the cause of this warning?

**Comment by CryptoManiac** [comment]
Nope, but it disappeared after I applied few trivial modifications to this function. I'll create pull request a bit later.
